#!/bin/sh
#debug=true
#nasm -f bin boot.asm -o boot.bin
#ndisasm -b 32 boot.bin | head
#rm boot.bin
#exit

qemu_cmd=(qemu-system-i386 -drive file=mios.img,index=0,media=disk,format=raw)

make clean
make all || exit
if [ -z $debug ]; then
  "${qemu_cmd[@]}"
else
  # Start QEMU in a detached screen session.
  screen -d -m "${qemu_cmd[@]}" -s -S
  sleep 1 # Give time for QEMU to start.
  # `e dbg.bpinmaps=false` allows placing breakpoints outside mapped memory.
  r2 -b 32 -d gdb://localhost:1234 -c 'e dbg.bpinmaps=false; db 0x80000; dc'
fi
make clean
